version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  database:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - 27017:27017
